runtime: nodejs14
instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
env_variables:
  BASE_URL: "https://acr-website-391905.nn.r.appspot.com"
  EMAIL_USER: "rustyvolts@gmail.com"
  EMAIL_PASS: "fjblmbbambhkcsll"
  RECIPIENT_EMAIL: "rustyvolts@gmail.com"
